### ISSUE TITLE
Cambio de Canal

### ISSUE THREAD

**Issue by eduardogt** [Vodker/wifimosys#2]
Excelente trabajo ante todo felicitaciones. Los errores que detecte son los siguientes.

1.- Al momento de capturar el hanshake tengo que cerrar la ventana que mata las conexiones a la red principal (desautentifica clientes) porque si no nunca obtiene el hankshake.

2.- Cuando el router al que le hacemos cambia de canal (por lo general cuando los usuarios lo apagan y vuelven a prender al ver que no tienen conexión a internet) la desautentificacion deja de funcionar y los usuarios vuelven a tener internet siendo el ataque fallido por ese detalle. Seria bueno que al cambiar de canal el script detecte el cambio y relance el ataque con el canal que cambio.

3.- Nueva Idea: Que detecte cuando apaguen el router y el script se ponga en pausa (porque seria muy obvio que el ataque siga cuando el router este apagado)

Son ideas para el script y espero que las tomes de la mejor manera. Felicitaciones nuevamente. Saludos!

**Comment by Vodker** [comment]
Gracias por las sugerencias, se irán añadiendo nuevas funcionalidades.
Saludos.

**Comment by PASTO666** [comment]
Baje a la 0.21 de nuevo pq me funciona Mejor! No me gusta el.deauth de la versión 0.22.. El de la 0.21 para mi es mas efectivo y se ve en vivo cuando le da deauth a la mac :) la 0.22 todo se queda igual la lista y no se sabe si lo esta deauth o nop. Voto por el deauth de la 0.21 si haces otra versión y eso de los canales como dijo el compañero es buena idea pq apagan mucho los router y hay que volver a hacer el attack pa auto cambia de canal el router cada ves que lo vuelven a encender.

**Comment by ketamuny** [comment]
yo solo quiero felicitar el excelente trabajo que te has currado y a animarte a que des continuidad a tu proyecto, un saludo y gracias por compartir tu tiempo y tu herramienta....

**Comment by Vodker** [comment]
Ahora se detecta el cambio de canal y se cierra el script.
El deauth se ha cambiado a mdk3.
Saludos.

**Comment by PASTO666** [comment]
hola de nuevo. me eh comprado la nueva alfa awus036ach (8812au).. leyendo el tema de la misma en wifisolutions hice lo que legan renan postio.. instale su driver modificado y su patch para airmon para que pudiera escaniar. con eso todas las apps y attacks me funcionan de maravillas menos tu wifimosys :( su wifi mosys .25 me escanea bn, saca a los clients bn, hace el  handshake bn, pero a la  hora de crear el fake ap ahi esta el fallo.. el la crea pero no se ve al publico :( y en realidad es la app mas que me gusta y esta alfa es una bestia en alcanse y todo!! seria buena que wifimosys funcione al 100% con ella. buen dia.
